create sequence patientid_seq;

create sequence patientdata_patientid_seq;

create sequence diagnosisdata_diagnosisid_seq;

create sequence mtbreviewdata_mtbreviewid_seq;

create sequence recommendationdata_recommendationid_seq;

create sequence lusubmittingphysician_subphysid_seq;

create sequence lusubmittingfacility_subfaciltiyid_seq;

create sequence lugenomictesttype_gentesttypeid_seq;

create sequence lugenemutation_genemutid_seq;

create sequence lurecommendationtype_rectypeid_seq;

create sequence lugene_geneid_seq;

create sequence customhistology_id_seq;

create sequence recommendationgenedata_recommendationgeneid_seq;

create sequence familtyhistogy_familyhistogyid_seq;

create sequence familyhistorydata_familyhistoryid_seq;

create sequence recommendationdrug_recommendationdrugid_seq;

create sequence geneticcounselinggenedata_geneticcounselinggeneid_seq;

create table patientdata
(
    patientid            integer default nextval('mtbtracking.patientdata_patientid_seq'::regclass) not null
        primary key,
    lastname             varchar,
    firstname            varchar,
    mrn                  varchar,
    patientexpired       varchar,
    expirepriormtbreview varchar,
    lastcheckdate        date,
    gender               varchar,
    race                 varchar,
    deathdate            date,
    ethnicity            varchar,
    patientsearchhash    varchar default ''::character varying,
    multi18enrollment    varchar,
    multi19enrollment    varchar,
    multi19cohort        varchar,
    "multi19cohort2Barm" varchar,
    birthdate            date,
    primalenrollment     varchar,
    oncolens_batch       integer,
    oncolens_exclude     text
);

comment on column patientdata.patientid is 'Unique patient id, generated by database';

comment on column patientdata.lastname is 'Patient last name';

comment on column patientdata.firstname is 'Patient first name';

comment on column patientdata.mrn is 'Medical record number';

comment on column patientdata.patientexpired is 'Yes/No for if patient has died';

comment on column patientdata.expirepriormtbreview is 'Yes/No if patient died prior to mtb review';

comment on column patientdata.lastcheckdate is 'Date survival data last checked';

comment on column patientdata.gender is 'Patient gender, dropdown; values not in database';

comment on column patientdata.race is 'Patient race, dropdown; values not in database';

comment on column patientdata.deathdate is 'Death date';

comment on column patientdata.ethnicity is 'Patient ethnicity, dropdown; values not in database';

comment on column patientdata.patientsearchhash is 'Internal field used for combining strings for search';

comment on column patientdata.multi18enrollment is 'Yes/No for if patient is enrolled to Multi18';

comment on column patientdata.multi19enrollment is 'Yes/No for if patient is enrolled to Multi19';

comment on column patientdata.multi19cohort is 'Multi19 cohort indication, dropdown; values not in database';

comment on column patientdata."multi19cohort2Barm" is 'Multi19 arm , dropdown; values not in database';

comment on column patientdata.birthdate is 'Patient date of birth';

comment on column patientdata.primalenrollment is 'Patient enrolled to PRiMAL project';


create table diagnosisdata
(
    diagnosisid        integer default nextval('mtbtracking.diagnosisdata_diagnosisid_seq'::regclass) not null
        primary key,
    diagnosissite      varchar,
    diagnosishistology varchar,
    diagnosisstage     varchar,
    patientid          integer
        references patientdata
            on delete cascade,
    externalid         varchar,
    diagnosisage       integer,
    diagnosisdate      date,
    diagnosisyear      integer,
    diagnosisyearonly  boolean,
    recurrencedate     date
);

comment on column diagnosisdata.diagnosisid is 'Unique id for diagnosis, generated by database';

comment on column diagnosisdata.diagnosissite is 'ICDO3 diagnosis site';

comment on column diagnosisdata.diagnosishistology is 'Histology';

comment on column diagnosisdata.diagnosisstage is 'Stage, 1-4';

comment on column diagnosisdata.patientid is 'Foreign key to patient';

comment on column diagnosisdata.externalid is 'This was used for data migration, not needed';

comment on column diagnosisdata.diagnosisage is 'Age at diagnosis';

comment on column diagnosisdata.diagnosisdate is 'Date of diagnosis';

comment on column diagnosisdata.diagnosisyear is 'Year of diagnosis';

comment on column diagnosisdata.diagnosisyearonly is 'Some diagnosis records we only have the year, this is a flag for this indication.';

comment on column diagnosisdata.recurrencedate is 'Date of recurrence, only applicable for Recurrent Disease for stage';



create table mtbreviewdata
(
    mtbreviewid                        integer default nextval('mtbtracking.mtbreviewdata_mtbreviewid_seq'::regclass) not null
        primary key,
    patientid                          integer
        references patientdata
            on delete cascade,
    diagnosisid                        integer
        references diagnosisdata
            on delete cascade,
    submittingphysician                varchar,
    submittingfacility                 varchar,
    casetype                           varchar,
    submissiondate                     date,
    reviewedbymtb                      varchar,
    reviewtype                         varchar,
    reviewdate                         date,
    casenumber                         integer,
    multi18enrollment                  varchar,
    currenttherapy                     text,
    genomictesttype                    varchar,
    externalid                         varchar,
    multi19enrollment                  varchar,
    mtbreviewage                       integer,
    therapyoutcomes                    varchar,
    germlinerecommendationaccepted     varchar,
    germlinerecommendationaccepteddate date,
    recommendationcurrenttherapy       varchar,
    germlinerecommendationreason       varchar,
    multi19cohort                      varchar,
    "multi19cohort2Barm"               varchar,
    germlinedeclinereason              text,
    othergenomictesttype               varchar,
    batch                              varchar,
    genetictestingresults              varchar
);

comment on column mtbreviewdata.mtbreviewid is 'Unique id for MTB Review record, generated by database';

comment on column mtbreviewdata.patientid is 'Foreign key to patient id';

comment on column mtbreviewdata.diagnosisid is 'Foreign key to diagnosis';

comment on column mtbreviewdata.submittingphysician is 'Submitting physician of review';

comment on column mtbreviewdata.submittingfacility is 'Submitting facility of review';

comment on column mtbreviewdata.casetype is 'Type of case for review, Adult or Pediatric';

comment on column mtbreviewdata.submissiondate is 'Date of submission';

comment on column mtbreviewdata.reviewedbymtb is 'Yes/No for if case was reviewed by MTB';

comment on column mtbreviewdata.reviewtype is 'Type of review, Administrative or MTB Meeting';

comment on column mtbreviewdata.reviewdate is 'Date of review';

comment on column mtbreviewdata.casenumber is 'Case number';

comment on column mtbreviewdata.multi18enrollment is 'This was moved to the patient level';

comment on column mtbreviewdata.currenttherapy is 'Current therapy for diagnosis';

comment on column mtbreviewdata.genomictesttype is 'Genomic test type, source is lugenomictesttype';

comment on column mtbreviewdata.externalid is 'Used for data migration, not needed';

comment on column mtbreviewdata.multi19enrollment is 'Not used, collected on patient level, data migrated';

comment on column mtbreviewdata.mtbreviewage is 'Age at review';

comment on column mtbreviewdata.therapyoutcomes is 'Therapy outcomes, uses same drug list as recommendationdrug';

comment on column mtbreviewdata.germlinerecommendationaccepted is 'Yes/No';

comment on column mtbreviewdata.germlinerecommendationaccepteddate is 'Date germline recommendation accepted';

comment on column mtbreviewdata.recommendationcurrenttherapy is 'No longer used';

comment on column mtbreviewdata.germlinerecommendationreason is 'Reason for germline recommendation, dropdown;values not stored in database';

comment on column mtbreviewdata.multi19cohort is 'Not used, collected on patient level, data migrated';

comment on column mtbreviewdata."multi19cohort2Barm" is 'Not used, collected on patient level, data migrated';

comment on column mtbreviewdata.germlinedeclinereason is 'No longer used';

comment on column mtbreviewdata.othergenomictesttype is 'If Other genomic test type selected, specify here';

comment on column mtbreviewdata.batch is 'Used for grouping reviews for presenting';

comment on column mtbreviewdata.genetictestingresults is 'No longer used';

create table recommendationdata
(
    recommendationid             integer default nextval('mtbtracking.recommendationdata_recommendationid_seq'::regclass) not null
        primary key,
    mtbreviewid                  integer                                                                                  not null
        references mtbreviewdata
            on delete cascade,
    patientid                    integer                                                                                  not null
        references patientdata
            on delete cascade,
    diagnosisid                  integer                                                                                  not null
        references diagnosisdata
            on delete cascade,
    recommendationtype           varchar,
    genename                     varchar,
    mutation                     varchar,
    evidencelevel                varchar,
    targetedtrial                varchar,
    nctnum                       varchar,
    uktrial                      varchar,
    drugname                     varchar,
    genefunction                 varchar,
    biomarker                    varchar,
    testforgene                  varchar,
    othertypedescription         text,
    recommendationnotes          text,
    recommendation               varchar,
    biomarkerscore               varchar,
    germlinerecommendationreason varchar,
    recommendationtimepoint      varchar,
    trial_accepted               text,
    last_checked                 date
);

comment on column recommendationdata.recommendationid is 'Unique id for record, generated by database';

comment on column recommendationdata.mtbreviewid is 'Foreign key to MTB Review data';

comment on column recommendationdata.patientid is 'Foreign key to patient data';

comment on column recommendationdata.diagnosisid is 'Foreign key to diagnosis data';

comment on column recommendationdata.recommendationtype is 'Type of recommendation';

comment on column recommendationdata.genename is 'Moved to recommendationgenedata';

comment on column recommendationdata.mutation is 'Moved to recommendationgenedata';

comment on column recommendationdata.evidencelevel is 'Evidence level, 1-4';

comment on column recommendationdata.targetedtrial is 'Targeted trial';

comment on column recommendationdata.nctnum is 'NCT Number';

comment on column recommendationdata.uktrial is 'Yes/No if UK trial';

comment on column recommendationdata.drugname is 'No longer used, the recommendation field took place for this one';

comment on column recommendationdata.genefunction is 'Gene function';

comment on column recommendationdata.biomarker is 'Moved to recommendationgenedata';

comment on column recommendationdata.testforgene is 'Yes/No Test for gene';

comment on column recommendationdata.othertypedescription is 'If type Other indicated for recommendation type, specify other type here';

comment on column recommendationdata.recommendationnotes is 'Recommendation notes';

comment on column recommendationdata.recommendation is 'Drug recommendations, source list is recommendationdrug';

comment on column recommendationdata.biomarkerscore is 'Moved to recommendationgenedata';

comment on column recommendationdata.germlinerecommendationreason is 'Germline recommendation reason, dropdown; values not in database';

comment on column recommendationdata.recommendationtimepoint is 'Recommendation timepoint, dropdown; values not in database';


create table lusubmittingphysician
(
    subphysid           integer default nextval('mtbtracking.lusubmittingphysician_subphysid_seq'::regclass) not null
        primary key,
    submittingphysician varchar
);


alter sequence lusubmittingphysician_subphysid_seq owned by lusubmittingphysician.subphysid;

create unique index lusp_name
    on lusubmittingphysician (submittingphysician);



create table lusubmittingfacility
(
    subfaciltiyid      integer default nextval('mtbtracking.lusubmittingfacility_subfaciltiyid_seq'::regclass) not null
        primary key,
    submittingfacility varchar
);


create table lugenomictesttype
(
    gentesttypeid   integer default nextval('mtbtracking.lugenomictesttype_gentesttypeid_seq'::regclass) not null,
    genomictesttype varchar
);


create table lugenemutation
(
    genemutid    integer default nextval('mtbtracking.lugenemutation_genemutid_seq'::regclass) not null
        primary key,
    genename     varchar,
    mutationname varchar
);



create table lurecommendationtype
(
    rectypeid          integer default nextval('mtbtracking.lurecommendationtype_rectypeid_seq'::regclass) not null,
    recommendationtype varchar
);


create table lugene
(
    geneid    integer default nextval('mtbtracking.lugene_geneid_seq'::regclass) not null
        primary key,
    genename  varchar,
    biomarker varchar
);



create table customhistology
(
    id          integer default nextval('mtbtracking.customhistology_id_seq'::regclass) not null
        primary key,
    behavior    varchar,
    code        varchar,
    description varchar
);


create table lubehaviorcode
(
    code        integer,
    description varchar
);



create table recommendationgenedata
(
    recommendationgeneid integer default nextval('mtbtracking.recommendationgenedata_recommendationgeneid_seq'::regclass) not null
        constraint recommenationgenedata_pkey
            primary key,
    recommendationid     integer                                                                                          not null
        constraint recommenationgenedata_recommendationid_fkey
            references recommendationdata
            on delete cascade,
    genename             varchar,
    genemutation         varchar,
    biomarkerscore       real
);

comment on column recommendationgenedata.recommendationgeneid is 'Unique id for record, generated by database';

comment on column recommendationgenedata.recommendationid is 'Foreign key to recommendation data, one recommendation can have multiple genes';

comment on column recommendationgenedata.genename is 'Name of gene or biomarker';

comment on column recommendationgenedata.genemutation is 'Mutation';

comment on column recommendationgenedata.biomarkerscore is 'Biomarker score';

create table familyhistorydata
(
    familyhistoryid         integer default nextval('mtbtracking.familyhistorydata_familyhistoryid_seq'::regclass) not null
        primary key,
    patientid               integer
        references patientdata
            on delete cascade,
    familyhistoryrelation   varchar,
    familyhistorysite       varchar,
    familyhistoryhistology  varchar,
    familyhistoryfamilyside varchar,
    otherfamilyhistory      varchar
);

comment on column familyhistorydata.familyhistoryid is 'Unique id for record, generated by database';

comment on column familyhistorydata.patientid is 'Foreign key to patient, one patient could have multiple familiy history records';

comment on column familyhistorydata.familyhistoryrelation is 'Relation of family, , dropdown; values not in database';

comment on column familyhistorydata.familyhistorysite is 'Diagnosis site of family member';

comment on column familyhistorydata.familyhistoryhistology is 'Histology of diagnosis of family member';

comment on column familyhistorydata.familyhistoryfamilyside is 'Side of family member, Maternal or Paternal';

comment on column familyhistorydata.otherfamilyhistory is 'Other information';


create table recommendationdrug
(
    recommendationdrugid integer default nextval('mtbtracking.recommendationdrug_recommendationdrugid_seq'::regclass) not null
        primary key,
    recommendationdrug   varchar
);


create table geneticcounselingdata
(
    geneticcounselingid           serial
        primary key,
    patientid                     integer
        references patientdata
            on update cascade on delete cascade,
    geneticcounselingreferraldate date,
    geneticcounselingseendate     date,
    testingordered                varchar(300),
    germlineresults               varchar(30),
    nogermlinetestingreason       varchar(500)
);

comment on column geneticcounselingdata.patientid is 'Joins to patientid in patientdata. These records are not specific to a diagnosis, review, or recommendation, only to a patient.';

comment on column geneticcounselingdata.geneticcounselingreferraldate is 'Genetic counseling referral date';

comment on column geneticcounselingdata.geneticcounselingseendate is 'Date patient seen for genetic counseling';

comment on column geneticcounselingdata.testingordered is 'Genetic counseling test';

comment on column geneticcounselingdata.germlineresults is 'Results';

comment on column geneticcounselingdata.nogermlinetestingreason is 'If no genetic counseling, reason.';


create table geneticcounselinggenedata
(
    geneticcounselinggeneid integer default nextval('mtbtracking.geneticcounselinggenedata_geneticcounselinggeneid_seq'::regclass) not null
        constraint geneticcounselinggenedata_pkey1
            primary key,
    geneticcounselingid     integer                                                                                                not null
        references geneticcounselingdata
            on update cascade on delete cascade,
    genename                varchar,
    genemutation            varchar
);

comment on column geneticcounselinggenedata.geneticcounselinggeneid is 'Unique id for record, generated by database';

comment on column geneticcounselinggenedata.geneticcounselingid is 'Foreign key to genetic counseling data, one genetic counseling record can have multiple genes';

comment on column geneticcounselinggenedata.genename is 'Name of gene or biomarker, uses lugene';

comment on column geneticcounselinggenedata.genemutation is 'Mutation, uses lugenemutation';



create table mtbreviewtesttypes
(
    id                   serial
        primary key,
    patientid            integer
        references patientdata
            on update cascade on delete cascade,
    diagnosisid          integer
        references diagnosisdata
            on update cascade on delete cascade,
    mtbreviewid          integer
        references mtbreviewdata
            on update cascade on delete cascade,
    genomictesttype      varchar,
    reportdate           date,
    collectiondate       date,
    specimentype         varchar,
    othergenomictesttype varchar
);



create view lookupsite(edition, topographycode, description, searchhash, storevalue) as
SELECT cdtopography.edition,
       btrim(cdtopography.topographycode::text)                                                                AS topographycode,
       btrim(cdtopography.description::text)                                                                   AS description,
       concat(btrim(cdtopography.topographycode::text),
              btrim(cdtopography.description::text))                                                           AS searchhash,
       concat_ws(' - '::text, btrim(cdtopography.topographycode::text),
                 btrim(cdtopography.description::text))                                                        AS storevalue
FROM cpdmsglobal.cdtopography
WHERE cdtopography.edition = '3'::bpchar;


create view lookuphistology
            (edition, histologycode, behaviorcode, behaviorcodedescription, histology, searchhash, storevalue,
             source) as
SELECT comp.edition,
       comp.histologycode,
       comp.behaviorcode,
       comp.behaviorcodedescription,
       comp.histology,
       comp.searchhash,
       comp.storevalue,
       comp.source
FROM (SELECT hist.edition,
             btrim(hist.histologycode::text)                                                                       AS histologycode,
             btrim(hist.behaviorcode::text)                                                                        AS behaviorcode,
             btrim(lu_bc.type::text)                                                                               AS behaviorcodedescription,
             btrim(hist.description::text)                                                                         AS histology,
             concat(btrim(hist.histologycode::text), btrim(hist.description::text),
                    'CPDMS')                                                                                       AS searchhash,
             concat(btrim(hist.histologycode::text), '/', hist.behaviorcode, ' - ',
                    btrim(hist.description::text))                                                                 AS storevalue,
             'CPDMS'::text                                                                                         AS source
      FROM cpdmsglobal.cdhistology hist
               LEFT JOIN cpdmsglobal.cdbehaviorcodes lu_bc ON lu_bc.code = hist.behaviorcode
      UNION ALL
      SELECT 'CUSTOM'::bpchar                                                                            AS edition,
             btrim(chist.code::text)                                                                     AS histologycode,
             btrim(chist.behavior::text)                                                                 AS behaviorcode,
             ''::text                                                                                    AS behaviorcodedescription,
             btrim(chist.description::text)                                                              AS histology,
             concat(btrim(chist.code::text), btrim(chist.description::text), 'CUSTOM')                   AS searchhash,
             concat(btrim(chist.code::text), '/', chist.behavior, ' - ', btrim(chist.description::text)) AS storevalue,
             'CUSTOM'::text                                                                              AS source
      FROM mtbtracking.customhistology chist) comp
WHERE comp.edition = ANY (ARRAY ['3'::bpchar, 'CUSTOM'::bpchar])
ORDER BY comp.edition, comp.histologycode, comp.behaviorcode;



create view druglist(value, display) as
SELECT a.value,
       a.display
FROM (SELECT DISTINCT recommendationdata.recommendation AS value,
                      recommendationdata.recommendation AS display
      FROM mtbtracking.recommendationdata) a
WHERE char_length(a.value::text) <> 0
ORDER BY a.value;



create view patientview
            (patientid, lastname, firstname, mrn, patientexpired, expirepriormtbreview, lastcheckdate, gender, race,
             birthdate, deathdate, ethnicity, multi18enrollment, multi19enrollment, multi19cohort, "multi19cohort2Barm",
             patientsearchhash, primalenrollment)
as
SELECT patientdata.patientid,
       patientdata.lastname,
       patientdata.firstname,
       patientdata.mrn,
       patientdata.patientexpired,
       patientdata.expirepriormtbreview,
       patientdata.lastcheckdate,
       patientdata.gender,
       patientdata.race,
       patientdata.birthdate,
       patientdata.deathdate,
       patientdata.ethnicity,
       patientdata.multi18enrollment,
       patientdata.multi19enrollment,
       patientdata.multi19cohort,
       patientdata."multi19cohort2Barm",
       patientdata.patientsearchhash,
       patientdata.primalenrollment
FROM mtbtracking.patientdata;



create function create_patient_search_hash_insert() returns trigger
    language plpgsql
as
$$BEGIN 
	NEW.patientsearchhash := CONCAT(lower(TRIM(NEW.lastname)), lower(TRIM(NEW.firstname)), lower(TRIM(NEW.mrn)), NEW.patientid);
	INSERT INTO mtbtracking.mtb_newpatient_debug (patientid, lastname, firstname, mrn, patienthash) VALUES (NEW.patientid,NEW.lastname,NEW.firstname,NEW.mrn,CONCAT(lower(TRIM(NEW.lastname)), lower(TRIM(NEW.firstname)), lower(TRIM(NEW.mrn)), NEW.patientid));
   RETURN NEW; 
END;$$;

alter function create_patient_search_hash_insert() owner to justin;

create function create_patient_search_hash() returns trigger
    language plpgsql
as
$$
BEGIN
	IF CONCAT(lower(OLD.lastname), lower(OLD.firstname), lower(OLD.mrn), OLD.patientid) != CONCAT(lower(NEW.lastname), lower(NEW.firstname), lower(NEW.mrn), NEW.patientid) OR NEW.patientsearchhash IS NULL THEN
		UPDATE mtbtracking.patientdata
		SET patientsearchhash = CONCAT(lower(NEW.lastname), lower(NEW.firstname), lower(NEW.mrn), NEW.patientid)
		WHERE OLD.patientid = patientid;
	END IF;
    RETURN NEW;
END;
$$;

alter function create_patient_search_hash() owner to justin;

create trigger after_update_patient_searchhash_trigger
    after update
    on patientdata
    for each row
execute procedure create_patient_search_hash();


